#CloudFormation template to create an S3 bucket
AWSTemplateFormatVersion: 2010-09-09
Description: Create an S3 bucket
Resources:
  UdaBucket:
    Type: AWS::S3::Bucket #Create an S3 bucket
    Properties:
      BucketName: uda-iye-bucket #name of the bucket very random in this case
      WebsiteConfiguration: #hold a static website
        IndexDocument: index.html 
        ErrorDocument: error.html
Outputs:
  WebsiteURL:
    Value: !GetAtt UdaBucket.WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !GetAtt UdaBucket.DomainName
    Description: Name of S3 bucket to hold website content
  